# Generated by Django 3.2 on 2021-04-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CS', ' classic'), ('OP', 'oilpainting')], default='CS', max_length=100),
            preserve_default=False,
        ),
    ]
