# Generated by Django 3.2 on 2021-04-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='ordered_date',
        ),
    ]
