# Generated by Django 3.2 on 2021-04-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='b_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
