# Generated by Django 3.2 on 2021-04-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210430_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimage',
            name='b_img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
